### ISSUE TITLE
RabbitMQ - Connection refused: localhost/127.0.0.1:61613

### ISSUE THREAD

**Issue by yeseong31** [yeseong31/spring-proj-chat#4]
- `docker-compose`로 Spring Boot와 MariaDB, RabbitMQ를 한 번에 실행하는 중에 오류가 발생하고 있다.

```yaml
version: "3"
services:
  database:
    container_name: database
    image: mariadb
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_HOST: '%'
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${DATABASE_USERNAME}
      MARIADB_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    restart: always
    networks:
      - spring-chat-net

  rabbitmq:
    image: yeseong31/rabbitmq-stomp
    container_name: rabbitmq_chat
    hostname: rabbitmq_container
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - spring-chat-net

  application:
    image: yeseong31/spring-chat-app
    container_name: spring_chat_app
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/${MARIADB_DATABASE}?characterEncoding=UTF-8&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - database
      - rabbitmq
    restart: always
    networks:
      - spring-chat-net

networks:
  spring-chat-net:
    driver: bridge
    external: true
```

- Spring Boot와 MariaDB는 연동이 잘 되어서 게시글 CRUD가 잘 되지만, **RabbitMQ는 아래의 메시지와 함께 연결이 실패하고 있다.**

```
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:61613
Caused by: java.net.ConnectException: Connection refused
```

**Comment by yeseong31** [comment]
- 문제는 **각 컨테이너가 서로의 정보를 몰라서 접속하지 못하는 것 때문이었다.**

- Docker는 **재시작할 때마다 컨테이너의 IP를 자동으로 할당해 주는데**, 매번 IP 주소가 바뀌는 바람에 **각 컨테이너가 서로의 정보를 몰라서 연동하지 못하는 것으로부터 비롯된 문제였다.**

- 이에 **모든 컨테이너에 고정 IP를 지정**하는 것으로 문제를 해결했다.

<br>

### docker-compose 실행

- 먼저 `docker-compose.yml` 파일에 네트워크 정의를 다음과 같이 해주었다.

- 이때 네트워크에 사설 서브넷을 `172.27.0.0/16`으로 생성했다.

```yaml
networks:  
  spring-chat-net:  
    ipam:  
      config:  
        - subnet: 172.27.0.0/16  
          gateway: 172.27.0.1
```

<br>

- 그다음으로 해당 서브넷에 대한 IPv4 주소를 각 서비스에 할당했다.

- 그전에 살펴보아야 할 것은 Spring Boot jar 파일이었다.

- 이전에 jar 파일 생성 당시 RabbitMQ와 MongoDB의 `HOST`를 다음과 같이 설정하여 `build`한 적이 있다.

```
# env.local.properties
RABBITMQ_HOST=172.27.0.4
MONGODB_HOST=172.27.0.2
```

<br>

- 당시에는 고정 IP를 적용하기 전이었기 때문에 수동으로 jar 파일에 RabbitMQ와 MongoDB의 `HOST` 정보를 저렇게 명시적으로 설정해놓고 배포를 했었다.

- 따라서 고정 IP를 설정하면서 헷갈리지 않도록 기존의 RabbitMQ, MongoDB의 IP 주소를 그대로 `docker-compose.yml` 파일에 작성하였고, MariaDB와 Spring Boot의 IP 주소를 새롭게 지정해주었다.

```yaml
version: "3"  
services:  
  database:  
    container_name: database  
    image: mariadb  
    environment:  
      MARIADB_DATABASE: ${MARIADB_DATABASE}  
      MARIADB_ROOT_HOST: '%'  
  MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}  
      MARIADB_USER: ${DATABASE_USERNAME}  
      MARIADB_PASSWORD: ${MARIADB_ROOT_PASSWORD}  
      TZ: 'Asia/Seoul'  
  ports:  
      - "3306:3306"  
  command:  
      - "--character-set-server=utf8mb4"  
	  - "--collation-server=utf8mb4_unicode_ci"  
  restart: always  
    networks:  
      spring-chat-net:  
        ipv4_address: 172.27.0.2  
  
  rabbitmq:  
    image: yeseong31/spring-rabbitmq  
    container_name: rabbitmq_chat  
    hostname: rabbitmq_container  
    ports:  
      - "5672:5672"  
	  - "25672:25672"  
	  - "15672:15672"  
	  - "15692:15692"  
	  - "61613:61613"  
  environment:  
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}  
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}  
    restart: always  
    networks:  
      spring-chat-net:  
        ipv4_address: 172.27.0.4  
  
  mongodb:  
    image: mongo  
    container_name: mongo_chat  
    restart: always  
    ports:  
      - "27017:27017"  
  volumes:  
      - ./mongodb:/data/db  
    environment:  
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}  
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}  
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE_NAME}  
    networks:  
      spring-chat-net:  
        ipv4_address: 172.27.0.3  
  
  application:  
    image: yeseong31/spring-chat-app  
    container_name: spring_chat_app  
    ports:  
      - "8080:8080"  
  environment:  
      SPRING_RABBITMQ_HOST: rabbitmq  
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/${MARIADB_DATABASE}?characterEncoding=UTF-8&serverTimezone=UTC  
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}  
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}  
    depends_on:  
      - database  
      - rabbitmq  
      - mongodb  
    restart: always  
    networks:  
      spring-chat-net:  
        ipv4_address: 172.27.0.5  
  
networks:  
  spring-chat-net:  
    ipam:  
      config:  
        - subnet: 172.27.0.0/16  
          gateway: 172.27.0.1
``` 

<br>

- 이후 `docker-compose.yml` 파일이 위치한 곳에서 터미널을 열고 다음의 명령어를 실행하여 컨테이너들을 배포했다.

```docker
docker compose --env-file ./src/main/resources/env.pass.properties up -d
```

> 여기서 `--env-file`로 환경 변수가 저장된 위치를 명시적으로 설정해 주었다.
> 설정해주지 않으면 기본 경로는 `.env`이다.

<br>

- 명령어를 실행하면 Docker Desktop에서 다음과 같이 컨테이너가 실행되는 모습을 확인할 수 있다.

![image](https://github.com/yeseong31/spring-proj-chat/assets/66625672/106439b6-0655-4859-92ec-5a1bdadcd5c6)

<br>

- 그리고 애플리케이션을 실행하면 정상적으로 RabbitMQ와 MongoDB가 연동되어서 데이터가 잘 저장되는 모습을 확인할 수 있었다.
